// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: context_domain_table_change.proto

package contextdomain_change

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _context_domain_table_change_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ContextDomainTableChangeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ContextDomainTableChangeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ContextDomainTableChangeRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ContextDomainTableChangeRequestMultiError, or nil if none found.
func (m *ContextDomainTableChangeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ContextDomainTableChangeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = ContextDomainTableChangeRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetField()) < 1 {
		err := ContextDomainTableChangeRequestValidationError{
			field:  "Field",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for OldValue

	// no validation rules for NewValue

	if err := m._validateUuid(m.GetContextTableDetailId()); err != nil {
		err = ContextDomainTableChangeRequestValidationError{
			field:  "ContextTableDetailId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ContextDomainTableChangeRequestMultiError(errors)
	}

	return nil
}

func (m *ContextDomainTableChangeRequest) _validateUuid(uuid string) error {
	if matched := _context_domain_table_change_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ContextDomainTableChangeRequestMultiError is an error wrapping multiple
// validation errors returned by ContextDomainTableChangeRequest.ValidateAll()
// if the designated constraints aren't met.
type ContextDomainTableChangeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContextDomainTableChangeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContextDomainTableChangeRequestMultiError) AllErrors() []error { return m }

// ContextDomainTableChangeRequestValidationError is the validation error
// returned by ContextDomainTableChangeRequest.Validate if the designated
// constraints aren't met.
type ContextDomainTableChangeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContextDomainTableChangeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContextDomainTableChangeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContextDomainTableChangeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContextDomainTableChangeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContextDomainTableChangeRequestValidationError) ErrorName() string {
	return "ContextDomainTableChangeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ContextDomainTableChangeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContextDomainTableChangeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContextDomainTableChangeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContextDomainTableChangeRequestValidationError{}
