// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: partners.proto

package partners

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	input "github.com/soustify/data-gateway-buffer-go/pkg/input"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = input.StatusRequest(0)

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _partners_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PartnersRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PartnersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersRequestMultiError, or nil if none found.
func (m *PartnersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PartnersRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PartnersRequest_EnStatus_InLookup[m.GetEnStatus()]; !ok {
		err := PartnersRequestValidationError{
			field:  "EnStatus",
			reason: "value must be in list [ENABLED DISABLED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := PartnersRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDocument()) > 200 {
		err := PartnersRequestValidationError{
			field:  "Document",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdDocumentType()); err != nil {
		err = PartnersRequestValidationError{
			field:  "IdDocumentType",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersRequestMultiError(errors)
	}

	return nil
}

func (m *PartnersRequest) _validateUuid(uuid string) error {
	if matched := _partners_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersRequestMultiError is an error wrapping multiple validation errors
// returned by PartnersRequest.ValidateAll() if the designated constraints
// aren't met.
type PartnersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersRequestMultiError) AllErrors() []error { return m }

// PartnersRequestValidationError is the validation error returned by
// PartnersRequest.Validate if the designated constraints aren't met.
type PartnersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersRequestValidationError) ErrorName() string { return "PartnersRequestValidationError" }

// Error satisfies the builtin error interface
func (e PartnersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersRequestValidationError{}

var _PartnersRequest_EnStatus_InLookup = map[input.StatusRequest]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on PartnersResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PartnersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersResponseMultiError, or nil if none found.
func (m *PartnersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PartnersResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdAuditable()); err != nil {
		err = PartnersResponseValidationError{
			field:  "IdAuditable",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := PartnersResponseValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDocument()) > 200 {
		err := PartnersResponseValidationError{
			field:  "Document",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdDocumentType()); err != nil {
		err = PartnersResponseValidationError{
			field:  "IdDocumentType",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersResponseMultiError(errors)
	}

	return nil
}

func (m *PartnersResponse) _validateUuid(uuid string) error {
	if matched := _partners_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersResponseMultiError is an error wrapping multiple validation errors
// returned by PartnersResponse.ValidateAll() if the designated constraints
// aren't met.
type PartnersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersResponseMultiError) AllErrors() []error { return m }

// PartnersResponseValidationError is the validation error returned by
// PartnersResponse.Validate if the designated constraints aren't met.
type PartnersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersResponseValidationError) ErrorName() string { return "PartnersResponseValidationError" }

// Error satisfies the builtin error interface
func (e PartnersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersResponseValidationError{}
