// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: partners_addresses.proto

package partners_addresses

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _partners_addresses_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PartnersAddressesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartnersAddressesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersAddressesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersAddressesRequestMultiError, or nil if none found.
func (m *PartnersAddressesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersAddressesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetIdPartner()); err != nil {
		err = PartnersAddressesRequestValidationError{
			field:  "IdPartner",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdAddress()); err != nil {
		err = PartnersAddressesRequestValidationError{
			field:  "IdAddress",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersAddressesRequestMultiError(errors)
	}

	return nil
}

func (m *PartnersAddressesRequest) _validateUuid(uuid string) error {
	if matched := _partners_addresses_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersAddressesRequestMultiError is an error wrapping multiple validation
// errors returned by PartnersAddressesRequest.ValidateAll() if the designated
// constraints aren't met.
type PartnersAddressesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersAddressesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersAddressesRequestMultiError) AllErrors() []error { return m }

// PartnersAddressesRequestValidationError is the validation error returned by
// PartnersAddressesRequest.Validate if the designated constraints aren't met.
type PartnersAddressesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersAddressesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersAddressesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersAddressesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersAddressesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersAddressesRequestValidationError) ErrorName() string {
	return "PartnersAddressesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartnersAddressesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersAddressesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersAddressesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersAddressesRequestValidationError{}

// Validate checks the field values on PartnersAddressesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartnersAddressesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersAddressesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersAddressesResponseMultiError, or nil if none found.
func (m *PartnersAddressesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersAddressesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PartnersAddressesResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdPartner()); err != nil {
		err = PartnersAddressesResponseValidationError{
			field:  "IdPartner",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdAddress()); err != nil {
		err = PartnersAddressesResponseValidationError{
			field:  "IdAddress",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersAddressesResponseMultiError(errors)
	}

	return nil
}

func (m *PartnersAddressesResponse) _validateUuid(uuid string) error {
	if matched := _partners_addresses_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersAddressesResponseMultiError is an error wrapping multiple validation
// errors returned by PartnersAddressesResponse.ValidateAll() if the
// designated constraints aren't met.
type PartnersAddressesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersAddressesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersAddressesResponseMultiError) AllErrors() []error { return m }

// PartnersAddressesResponseValidationError is the validation error returned by
// PartnersAddressesResponse.Validate if the designated constraints aren't met.
type PartnersAddressesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersAddressesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersAddressesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersAddressesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersAddressesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersAddressesResponseValidationError) ErrorName() string {
	return "PartnersAddressesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PartnersAddressesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersAddressesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersAddressesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersAddressesResponseValidationError{}
