// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: addresses.proto

package addresses

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	input "github.com/soustify/data-gateway-buffer-go/pkg/input"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = input.StatusRequest(0)

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _addresses_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AddressesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddressesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddressesRequestMultiError, or nil if none found.
func (m *AddressesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AddressesRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AddressesRequest_EnStatus_InLookup[m.GetEnStatus()]; !ok {
		err := AddressesRequestValidationError{
			field:  "EnStatus",
			reason: "value must be in list [ENABLED DISABLED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStreet()) > 200 {
		err := AddressesRequestValidationError{
			field:  "Street",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Number

	if val := m.GetLatitude(); val < -90 || val > 90 {
		err := AddressesRequestValidationError{
			field:  "Latitude",
			reason: "value must be inside range [-90, 90]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetLongitude(); val < -180 || val > 180 {
		err := AddressesRequestValidationError{
			field:  "Longitude",
			reason: "value must be inside range [-180, 180]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetZipCode()); l < 1 || l > 200 {
		err := AddressesRequestValidationError{
			field:  "ZipCode",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetComplement()) > 200 {
		err := AddressesRequestValidationError{
			field:  "Complement",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetNeighborhood()) > 200 {
		err := AddressesRequestValidationError{
			field:  "Neighborhood",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddressesRequestMultiError(errors)
	}

	return nil
}

func (m *AddressesRequest) _validateUuid(uuid string) error {
	if matched := _addresses_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AddressesRequestMultiError is an error wrapping multiple validation errors
// returned by AddressesRequest.ValidateAll() if the designated constraints
// aren't met.
type AddressesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressesRequestMultiError) AllErrors() []error { return m }

// AddressesRequestValidationError is the validation error returned by
// AddressesRequest.Validate if the designated constraints aren't met.
type AddressesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressesRequestValidationError) ErrorName() string { return "AddressesRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddressesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressesRequestValidationError{}

var _AddressesRequest_EnStatus_InLookup = map[input.StatusRequest]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on AddressesResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddressesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddressesResponseMultiError, or nil if none found.
func (m *AddressesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AddressesResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdAuditable()); err != nil {
		err = AddressesResponseValidationError{
			field:  "IdAuditable",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStreet()) > 200 {
		err := AddressesResponseValidationError{
			field:  "Street",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Number

	if val := m.GetLatitude(); val < -90 || val > 90 {
		err := AddressesResponseValidationError{
			field:  "Latitude",
			reason: "value must be inside range [-90, 90]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetLongitude(); val < -180 || val > 180 {
		err := AddressesResponseValidationError{
			field:  "Longitude",
			reason: "value must be inside range [-180, 180]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetZipCode()); l < 1 || l > 200 {
		err := AddressesResponseValidationError{
			field:  "ZipCode",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetComplement()) > 200 {
		err := AddressesResponseValidationError{
			field:  "Complement",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetNeighborhood()) > 200 {
		err := AddressesResponseValidationError{
			field:  "Neighborhood",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddressesResponseMultiError(errors)
	}

	return nil
}

func (m *AddressesResponse) _validateUuid(uuid string) error {
	if matched := _addresses_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AddressesResponseMultiError is an error wrapping multiple validation errors
// returned by AddressesResponse.ValidateAll() if the designated constraints
// aren't met.
type AddressesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressesResponseMultiError) AllErrors() []error { return m }

// AddressesResponseValidationError is the validation error returned by
// AddressesResponse.Validate if the designated constraints aren't met.
type AddressesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressesResponseValidationError) ErrorName() string {
	return "AddressesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddressesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressesResponseValidationError{}
