// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: partners_users.proto

package partners_users

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	input "github.com/soustify/data-gateway-buffer-go/pkg/input"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = input.StatusRequest(0)

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _partners_users_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on PartnersUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartnersUsersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersUsersRequestMultiError, or nil if none found.
func (m *PartnersUsersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersUsersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _PartnersUsersRequest_EnStatus_InLookup[m.GetEnStatus()]; !ok {
		err := PartnersUsersRequestValidationError{
			field:  "EnStatus",
			reason: "value must be in list [ENABLED DISABLED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetIdPartner()); l < 1 || l > 200 {
		err := PartnersUsersRequestValidationError{
			field:  "IdPartner",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := PartnersUsersRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 1 || l > 200 {
		err := PartnersUsersRequestValidationError{
			field:  "Username",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Enabled

	if err := m._validateUuid(m.GetIdCognito()); err != nil {
		err = PartnersUsersRequestValidationError{
			field:  "IdCognito",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersUsersRequestMultiError(errors)
	}

	return nil
}

func (m *PartnersUsersRequest) _validateUuid(uuid string) error {
	if matched := _partners_users_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersUsersRequestMultiError is an error wrapping multiple validation
// errors returned by PartnersUsersRequest.ValidateAll() if the designated
// constraints aren't met.
type PartnersUsersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersUsersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersUsersRequestMultiError) AllErrors() []error { return m }

// PartnersUsersRequestValidationError is the validation error returned by
// PartnersUsersRequest.Validate if the designated constraints aren't met.
type PartnersUsersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersUsersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersUsersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersUsersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersUsersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersUsersRequestValidationError) ErrorName() string {
	return "PartnersUsersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartnersUsersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersUsersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersUsersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersUsersRequestValidationError{}

var _PartnersUsersRequest_EnStatus_InLookup = map[input.StatusRequest]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on PartnersUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartnersUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartnersUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartnersUsersResponseMultiError, or nil if none found.
func (m *PartnersUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PartnersUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = PartnersUsersResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetIdPartner()); l < 1 || l > 200 {
		err := PartnersUsersResponseValidationError{
			field:  "IdPartner",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := PartnersUsersResponseValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 1 || l > 200 {
		err := PartnersUsersResponseValidationError{
			field:  "Username",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Enabled

	if err := m._validateUuid(m.GetIdCognito()); err != nil {
		err = PartnersUsersResponseValidationError{
			field:  "IdCognito",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdAuditable()); err != nil {
		err = PartnersUsersResponseValidationError{
			field:  "IdAuditable",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartnersUsersResponseMultiError(errors)
	}

	return nil
}

func (m *PartnersUsersResponse) _validateUuid(uuid string) error {
	if matched := _partners_users_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartnersUsersResponseMultiError is an error wrapping multiple validation
// errors returned by PartnersUsersResponse.ValidateAll() if the designated
// constraints aren't met.
type PartnersUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartnersUsersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartnersUsersResponseMultiError) AllErrors() []error { return m }

// PartnersUsersResponseValidationError is the validation error returned by
// PartnersUsersResponse.Validate if the designated constraints aren't met.
type PartnersUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartnersUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartnersUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartnersUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartnersUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartnersUsersResponseValidationError) ErrorName() string {
	return "PartnersUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PartnersUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartnersUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartnersUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartnersUsersResponseValidationError{}
