// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin_users.proto

package admin_users

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	input "github.com/soustify/data-gateway-buffer-go/pkg/input"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = input.StatusRequest(0)

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _admin_users_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AdminUsersRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AdminUsersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminUsersRequestMultiError, or nil if none found.
func (m *AdminUsersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminUsersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AdminUsersRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AdminUsersRequest_EnStatus_InLookup[m.GetEnStatus()]; !ok {
		err := AdminUsersRequestValidationError{
			field:  "EnStatus",
			reason: "value must be in list [ENABLED DISABLED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := AdminUsersRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = AdminUsersRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetIdCognito()); l < 1 || l > 200 {
		err := AdminUsersRequestValidationError{
			field:  "IdCognito",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdRoleApplication()); err != nil {
		err = AdminUsersRequestValidationError{
			field:  "IdRoleApplication",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AdminUsersRequestMultiError(errors)
	}

	return nil
}

func (m *AdminUsersRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *AdminUsersRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

func (m *AdminUsersRequest) _validateUuid(uuid string) error {
	if matched := _admin_users_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AdminUsersRequestMultiError is an error wrapping multiple validation errors
// returned by AdminUsersRequest.ValidateAll() if the designated constraints
// aren't met.
type AdminUsersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminUsersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminUsersRequestMultiError) AllErrors() []error { return m }

// AdminUsersRequestValidationError is the validation error returned by
// AdminUsersRequest.Validate if the designated constraints aren't met.
type AdminUsersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminUsersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminUsersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminUsersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminUsersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminUsersRequestValidationError) ErrorName() string {
	return "AdminUsersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AdminUsersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminUsersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminUsersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminUsersRequestValidationError{}

var _AdminUsersRequest_EnStatus_InLookup = map[input.StatusRequest]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on AdminUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminUsersResponseMultiError, or nil if none found.
func (m *AdminUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AdminUsersResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdAuditable()); err != nil {
		err = AdminUsersResponseValidationError{
			field:  "IdAuditable",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 200 {
		err := AdminUsersResponseValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = AdminUsersResponseValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetIdCognito()); l < 1 || l > 200 {
		err := AdminUsersResponseValidationError{
			field:  "IdCognito",
			reason: "value length must be between 1 and 200 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdRoleApplication()); err != nil {
		err = AdminUsersResponseValidationError{
			field:  "IdRoleApplication",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AdminUsersResponseMultiError(errors)
	}

	return nil
}

func (m *AdminUsersResponse) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *AdminUsersResponse) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

func (m *AdminUsersResponse) _validateUuid(uuid string) error {
	if matched := _admin_users_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AdminUsersResponseMultiError is an error wrapping multiple validation errors
// returned by AdminUsersResponse.ValidateAll() if the designated constraints
// aren't met.
type AdminUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminUsersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminUsersResponseMultiError) AllErrors() []error { return m }

// AdminUsersResponseValidationError is the validation error returned by
// AdminUsersResponse.Validate if the designated constraints aren't met.
type AdminUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminUsersResponseValidationError) ErrorName() string {
	return "AdminUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AdminUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminUsersResponseValidationError{}
