// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: categories_services.proto

package categories_services

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	input "github.com/soustify/data-gateway-buffer-go/pkg/input"

	output "github.com/soustify/data-gateway-buffer-go/pkg/output"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = input.StatusRequest(0)

	_ = output.StatusResponse(0)
)

// define the regex for a UUID once up-front
var _categories_services_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CategoriesServicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CategoriesServicesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CategoriesServicesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CategoriesServicesRequestMultiError, or nil if none found.
func (m *CategoriesServicesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CategoriesServicesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = CategoriesServicesRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CategoriesServicesRequest_EnStatus_InLookup[m.GetEnStatus()]; !ok {
		err := CategoriesServicesRequestValidationError{
			field:  "EnStatus",
			reason: "value must be in list [ENABLED DISABLED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdCategory()); err != nil {
		err = CategoriesServicesRequestValidationError{
			field:  "IdCategory",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdService()); err != nil {
		err = CategoriesServicesRequestValidationError{
			field:  "IdService",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CategoriesServicesRequestMultiError(errors)
	}

	return nil
}

func (m *CategoriesServicesRequest) _validateUuid(uuid string) error {
	if matched := _categories_services_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CategoriesServicesRequestMultiError is an error wrapping multiple validation
// errors returned by CategoriesServicesRequest.ValidateAll() if the
// designated constraints aren't met.
type CategoriesServicesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CategoriesServicesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CategoriesServicesRequestMultiError) AllErrors() []error { return m }

// CategoriesServicesRequestValidationError is the validation error returned by
// CategoriesServicesRequest.Validate if the designated constraints aren't met.
type CategoriesServicesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoriesServicesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoriesServicesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoriesServicesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoriesServicesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoriesServicesRequestValidationError) ErrorName() string {
	return "CategoriesServicesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CategoriesServicesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategoriesServicesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoriesServicesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoriesServicesRequestValidationError{}

var _CategoriesServicesRequest_EnStatus_InLookup = map[input.StatusRequest]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on CategoriesServicesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CategoriesServicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CategoriesServicesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CategoriesServicesResponseMultiError, or nil if none found.
func (m *CategoriesServicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CategoriesServicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = CategoriesServicesResponseValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if err := m._validateUuid(m.GetIdAuditable()); err != nil {
		err = CategoriesServicesResponseValidationError{
			field:  "IdAuditable",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdCategory()); err != nil {
		err = CategoriesServicesResponseValidationError{
			field:  "IdCategory",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetIdService()); err != nil {
		err = CategoriesServicesResponseValidationError{
			field:  "IdService",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CategoriesServicesResponseMultiError(errors)
	}

	return nil
}

func (m *CategoriesServicesResponse) _validateUuid(uuid string) error {
	if matched := _categories_services_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CategoriesServicesResponseMultiError is an error wrapping multiple
// validation errors returned by CategoriesServicesResponse.ValidateAll() if
// the designated constraints aren't met.
type CategoriesServicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CategoriesServicesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CategoriesServicesResponseMultiError) AllErrors() []error { return m }

// CategoriesServicesResponseValidationError is the validation error returned
// by CategoriesServicesResponse.Validate if the designated constraints aren't met.
type CategoriesServicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoriesServicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoriesServicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoriesServicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoriesServicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoriesServicesResponseValidationError) ErrorName() string {
	return "CategoriesServicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CategoriesServicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategoriesServicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoriesServicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoriesServicesResponseValidationError{}
